### ISSUE TITLE
Add "quick-run" and keyboard short-cut

### ISSUE THREAD

**Issue by Hirse** [caphodel/brackets-runscript#1]
I would like to have a keyboard short-cut that I can use to trigger the run in the most fitting language without have to use the mouse and selecting how I want to run it.

To select the language, I would think that taking the current documents language makes the most sense.
So for example, if the language is "JavaScript" or "HTML", use `runjs`.

**Comment by caphodel** [comment]
Well, that's a good idea, I'll do some code for it in a couples of day, please wait for it :)

**Comment by caphodel** [comment]
It is done, you can test it with the version 0.5.0 i just released.
If you have another ideas, bugs or something off with this release don't hesitate to contact me or fill an issue

**Comment by Hirse** [comment]
Thanks for the quick solution.
One issue though:
`Ctrl` + `R` is already used by [Rename JavaScript Identifier](https://github.com/asgerf/bracket-rename).
Could you change the shortcut to `Ctrl` + `Shift` + `R` for example?

**Comment by caphodel** [comment]
No problem, I'll make a quick fix

**Comment by caphodel** [comment]
I change it into F9, because Ctrl-Shift-R already used in another extension (I think it is live reload preview)

**Comment by Hirse** [comment]
Nice, thanks.
